# Generated by Django 3.2 on 2021-04-23 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
        ('theater', '0002_auto_20210422_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtiming',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='show_movie', to='movie.movie'),
        ),
    ]
