# Generated by Django 3.2 on 2021-04-23 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0002_auto_20210422_2328'),
        ('booking', '0002_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Seat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='theater.seat'),
        ),
    ]
