# Generated by Django 3.2 on 2021-04-23 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_seat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='Seat',
            new_name='seat',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='ShowTiming',
            new_name='show_timing',
        ),
    ]
